from datetime import timedelta
from typing import Any

from scipy import stats


DEFAULT_STATIONS: dict[int, dict[str, Any]] = {
    0: {
        "id": 0,
        "name": "Coinflip Cove",
        "rule_name": "geometric",
        "rule": stats.geom(p=0.30),
        "times_visited": 0,
        "waited_at": timedelta(),
        "N": None,
        "S": None,
        "E": 1,
        "W": None,
        "coordinates": (0, 0),
    },
    1: {
        "id": 1,
        "name": "Patience Point",
        "rule_name": "n_binomial",
        "rule": stats.nbinom(n=4, p=0.40),
        "times_visited": 0,
        "waited_at": timedelta(),
        "N": None,
        "S": 3,
        "E": 2,
        "W": 0,
        "coordinates": (1, 0),
    },
    2: {
        "id": 2,
        "name": "Poisson Plaza",
        "rule_name": "poisson",
        "rule": stats.poisson(mu=3.0),
        "times_visited": 0,
        "waited_at": timedelta(),
        "N": None,
        "S": None,
        "E": None,
        "W": 1,
        "coordinates": (2, 0),
    },
    3: {
        "id": 3,
        "name": "Binomial Bazaar",
        "rule_name": "binomial",
        "rule": stats.binom(n=10, p=0.35),
        "times_visited": 0,
        "waited_at": timedelta(),
        "N": 1,
        "S": 4,
        "E": None,
        "W": None,
        "coordinates": (1, 1),
    },
    4: {
        "id": 4,
        "name": "Dice Depot",
        "rule_name": "discrete_uniform",
        "rule": stats.randint(low=1, high=7),
        "times_visited": 0,
        "waited_at": timedelta(),
        "N": 3,
        "S": None,
        "E": None,
        "W": None,
        "coordinates": (1, 2),
    },
}
